def _generate_file_impl(ctx):
    output = ctx.actions.declare_file(ctx.attr.name + ".txt")

    ctx.actions.write(
        output = output,
        content = "Generated by custom Bazel rule\n",
    )

    return [DefaultInfo(files = depset([output]))]


generate_file = rule(
    implementation = _generate_file_impl,
)